name: Service container example
# Based on https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
on:
  - push
  - workflow_dispatch

env:
  POSTGRES_PASSWORD: postgres

jobs:
  executing-job-in-a-container:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # We don't need to map ports in this case as we're in the same docker bridge network

    steps:
      - name: Install psql
        run: |
          apk update
          apk add postgresql-client
      - name: Setup database tables
        run: |
          psql -h postgres -U postgres -c "
            create table todo
            (
                id   serial,
                task varchar not null,
                done boolean
            );
  
            insert into todo (task, done) values ('Task 1', FALSE);
            insert into todo (task, done) values ('Task 2', FALSE);
            insert into todo (task, done) values ('Task 3', FALSE);"